version: 0.2

phases:
  pre_build:
    commands:
      # Login to ECR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
      # Clone source code
      - echo Cloning repositories...
      - git clone --depth 1 https://github.com/providence-replay/providence.git ./

      # Set environment variables for build
      - echo Setting up variables...
      - export IMAGE_TAG=latest
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/providence-api
      
  build:
    commands:
      # Build the Docker image using backend Dockerfile
      - echo Building Providence API image...
      - docker build --target production -t $REPOSITORY_URI:$IMAGE_TAG -f ./backend/Dockerfile ./
      
  post_build:
    commands:
      # Push to ECR
      - echo Pushing to Amazon ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG