AWSTemplateFormatVersion: '2010-09-09'
Description: 'Providence CodeBuild Infrastructure Stack'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging

Resources:
  # ECR Repository
  ProvidenceApiRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: RetainExceptOnCreate
    Properties:
      RepositoryName: providence-api
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: MUTABLE

  # CodeBuild Service Role
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "providence-${Environment}-CodeBuildRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ProvidenceCodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/providence-${Environment}-build"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/providence-${Environment}-build:log-stream:*"
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/providence-api"
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: "*"

  # CodeBuild Project
  ProvidenceCodeBuildProject:
    Type: AWS::CodeBuild::Project
    DependsOn: ProvidenceApiRepository
    Properties:
      Name: !Sub "providence-${Environment}-build"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
      Source:
        Type: NO_SOURCE
      TimeoutInMinutes: 30

Outputs:
  EcrRepositoryUri:
    Description: URI of the ECR repository
    Value: !GetAtt ProvidenceApiRepository.RepositoryUri
    Export:
      Name: !Sub "providence-${Environment}-ecr-uri"

  CodeBuildProjectName:
    Description: Name of the CodeBuild project
    Value: !Ref ProvidenceCodeBuildProject
    Export:
      Name: !Sub "providence-${Environment}-codebuild-project"